LABEL batocera.linux
  LINUX /boot/linux
  FDT /boot/rk3588s-elo-backpack5.dtb
  APPEND initrd=/boot/initrd.lz4 label=BATOCERA partition_type=generic rootwait loglevel=8 console=ttyS2,1500000 coherent_pool=2M
