SectionVerb {
	Value {
		TQ "HiFi"
	}

	EnableSequence [
		cset "name='stream0.vol_ctrl0 MultiMedia1 Playback Volu' 8192"
		cset "name='SECONDARY_MI2S_RX Audio Mixer MultiMedia1' 1"
	]

	DisableSequence [
		cset "name='SECONDARY_MI2S_RX Audio Mixer MultiMedia1' 0"
	]
}

SectionDevice."Speakers" {
	Comment "Built-in speakers"

	EnableSequence [
		cset "name='Left Playback Volume' 950"
		cset "name='Right Playback Volume' 950"
	]

	DisableSequence [
		cset "name='Left Playback Volume' 0"
		cset "name='Right Playback Volume' 0"
	]

	# software volume now
	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},0"
		PlaybackChannels 2
	}
}
